apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-notes
  labels:
    app: my-notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-notes
  template:
    metadata:
      labels:
        app: my-notes
    spec:
      containers:
        - name: my-notes
          image: likhithsm/my-notes:latest
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: my-notes
spec:
  type: NodePort
  selector:
    app: my-notes
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
